version: "3.8"
services:

  online-app:
    image: online_shop:latest
    container_name: "online-app"
    ports:
      - "5173:5173"
    networks:
      - my-ntw

  nginx:
    image: nginx:latest
    container_name: "nginx-cont"
    ports:
      - "80:80"
    networks:
      - my-ntw

networks:
  my-ntw:
